name: Release library and dispatcher

on:
  workflow_dispatch

env:
  LIB_VERSION: 1.1.59
  DISPATCHER_VERSION: 1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        clean: 'true'
        fetch-depth: 0
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle clean
      run: ./gradlew clean --info
    - name: Build with Gradle
      run: ./gradlew kotlinUpgradeYarnLock :DefaultNetworkDispatcher:build :GrowthBook:build --info
#    - name: release
#      uses: actions/create-release@v1
#      id: create_release
#      with:
#        draft: false
#        prerelease: false
#        release_name: $LIB_VERSION
#        tag_name: $LIB_VERSION
#        body: ${{ github.event.head_commit.message }}
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to maven central
      run: |
        GPG_PRIVATE_KEY="${{secrets.GPG_PRIVATE_KEY}}" GPG_PRIVATE_PASSWORD="${{secrets.GPG_PRIVATE_PASSWORD}}" GB_SONATYPE_USERNAME='${{secrets.GB_SONATYPE_USERNAME}}' GB_SONATYPE_PASSWORD='${{secrets.GB_SONATYPE_PASSWORD}}' ./gradlew -Pversion=$LIB_VERSION :GrowthBook:publish -Pversion=$DISPATCHER_VERSION :DefaultNetworkDispatcher:publish
    - name: Upload binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: GrowthBook/build/libs/GrowthBook-jvm-${{ steps.gitversion.outputs.SemVer }}.jar
        asset_name: GrowthBook-$LIB_VERSION.jar
        asset_content_type: application/x-jar
    - name: Upload sources
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: GrowthBook/build/libs/GrowthBook-kotlin-$LIB_VERSION-sources.jar
        asset_name: GrowthBook-kotlin-${{ steps.gitversion.outputs.SemVer }}-sources.jar
        asset_content_type: application/x-jar
    - name: Upload metadata
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: GrowthBook/build/libs/GrowthBook-metadata-$LIB_VERSION.jar
        asset_name: GrowthBook-metadata-$LIB_VERSION-all.jar
        asset_content_type: application/x-jar
