name: Test coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate kover coverage report
        run: ./gradlew koverXmlReport

      - name: Save PR number
        run: echo ${{ github.event.number }} > pr-number.txt

      - name: Upload report and PR number
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            build/reports/kover/report.xml
            pr-number.txt
