name: Tests

on:
  push:
    branches:
      - '**'
      - '!main'
    tags-ignore:
      - '**'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean
      run: ./gradlew clean
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run test command
      run: ./gradlew test
